; Auto-generated by Boot, regenerate by executing: 'boot lein-generate'
(defproject
  collin/puu
  "0.1.0"
  :dependencies
  [[org.clojure/clojure "1.8.0"]
   [adzerk/boot-test "1.1.0" :scope "test"]
   [instaparse "1.4.1" :scope "test"]])